### ISSUE TITLE
Does not work with JDK 8 bsed project

### ISSUE THREAD

**Issue by rvsoni** [castor-software/depclean#25] opened 2020-12-04 12:46 UTC
The plugin is built on Java 11, so not possible to use with a project using jdk 8. 

Throws exception,

`[ERROR] Failed to execute goal se.kth.castor:depclean-maven-plugin:1.1.0:depclean (default) on project idsk-commons-media: Execution default of goal se.kth.castor:depclean-maven-plugin:1.1.0:depclean failed: An API incompatibility was encountered while executing se.kth.castor:depclean-maven-plugin:1.1.0:depclean: java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
`

**Comment by cesarsotovalero** [comment] 2020-12-04 22:05
@rvsoni We downgraded DepClean to Java 8 (see https://github.com/castor-software/depclean/commit/2faeb21a7cd928263cd01e06218e57ec17e2b5ee).

Does it work now for you?

**Comment by rvsoni** [comment] 2020-12-05 12:44
Thanks for updating for JDK8, 

I guess, You will have to make a release of this plugin, as the current 1.1.0 release is with JDK11 support and available from public Maven Repo, so the new release has to push on the Maven repo with an updated version so we can start using this maven plugin. 

I tested fix locally by building the project, 

Thanks,
Ravi

**Comment by cesarsotovalero** [comment] 2020-12-09 21:40
Hi @rvsoni, DepClean is available for JDK 8 in Maven Central. See it at https://search.maven.org/artifact/se.kth.castor/depclean-parent-pom/1.1.0/pom

Please close this issue if it works for you.
Also, consider giving this project a ⭐, it helps us to grow.
Thanks.

**Comment by rvsoni** [comment] 2020-12-12 17:15
Hi, @cesarsotovalero 

I don't think only updating deapclean-parent-pom:1.1.0 to jdk 8 is enough, I see the same error as only patent pom is updated but the deapclean-maven-plugin is still old jdk11 build,

The maven plugin code for deapclean-maven-plugin:1.1.0 is still old and compiled using JDK11, it's not going to work with jdk8,

MAINFEST.MF of dealclean-maven-plugin:1.1.0
https://repo1.maven.org/maven2/se/kth/castor/depclean-maven-plugin/1.1.0/depclean-maven-plugin-1.1.0.jar

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.3
Built-By: cesarsv
Build-Jdk: 11.0.7

```

You need to recompile all dealclean-maven-plugin code with jdk8 and republish to maven repo to make it working with jdk8.

Thanks,
Ravi

**Comment by amottier** [comment] 2021-01-14 18:47
I get the same issue with version `1.1.1` so I tried to investigate a little bit more.

Error is related probably to usage of `java.nio.ByteBuffer` in: https://github.com/castor-software/depclean/blob/master/depclean-core/src/main/java/se/kth/depclean/core/analysis/asm/ConstantPoolParser.java

A [comment](https://github.com/castor-software/depclean/blob/c519110c5bd38045564a650bc2ffef5b4ac7fbc0/depclean-core/src/main/java/se/kth/depclean/core/analysis/asm/ConstantPoolParser.java#L163) mention a workaround to this issue but is not implemented.

I run `javap -verbose ConstantPoolParser` on `ConstantPoolParser.class` packaged in `depclean-core-1.1.1.jar` and get the following output:
```
  minor version: 0
  major version: 52
```

According to https://en.wikipedia.org/wiki/Java_class_file#General_layout this confirm that this is some byte code targeting Java 8 even if `META-INF/MANIFEST.MF` packaged in `depclean-core-1.1.1.jar` mention `Build-Jdk: 15.0.1`: JDK 15 can generate byte code for Java 8.

An explanation about this behavior can be found in https://github.com/eclipse/jetty.project/issues/3244#issuecomment-495322586

Actually current pom.xml specify source and target (https://github.com/castor-software/depclean/blob/master/pom.xml#L19) but if Java 9 or higher is used to build the project it should specify the release option (`maven.compiler.release`) see https://stackoverflow.com/a/43103038/2440340

I will shortly create a pull request that fix the issue and allow successful build on Java 9 or higher (but note that build will failed with Java 8) with error `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project depclean-core: Fatal error compiling: invalid flag: --release -> [Help 1]`)

I'm not sure if there is an easy solution to allow build of the project with both Java 8 and Java 9+ versions. I guess that requiring Java 9+ version for building is not a big issue and that compatibility with Java 8+ version is what is important here.

**Comment by cesarsotovalero** [comment] 2021-01-14 22:07
@amottier Thanks for the detailed explanation and the PR. For the moment, DepClean is targeting Java 8 bytecode, so specifying the release option as you suggest should fix this issue. I'll merge https://github.com/castor-software/depclean/pull/29. 

@rvsoni WDYT?

**Comment by rvsoni** [comment] 2021-01-15 16:52
Hi @cesarsotovalero 

I don't think any code change is required, it needs just one fix related to the maven-compiler-plugin, just forked the existing code and made changes into the "depclean-parent-pom" as follow

Removed 
`        <maven.compiler.release>8</maven.compiler.release>`
 
Added
```
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```

Compiled the code with openjdk version "1.8.0_275" and tested the plugin with "Apache Commons Lang 3.10.1-SNAPSHOT" project,

You can see the project compilation log file ([depclean-jdk8.txt](https://github.com/castor-software/depclean/files/5821795/depclean-jdk8.txt)) and use of the plugin on "Apache Commons Lang 3.10.1-SNAPSHOT".
pl. review the fix I made and try on jdk 8

Note: pl. clean up your local maven repo folder "/.m2/repository/se/kth/castor/" before compliation to get clean reasult.

**Comment by amottier** [comment] 2021-01-15 18:19
@rvsoni I agree that using `maven.compiler.source` and `maven.compiler.target` properties and run the build using JDK 8 (need to update the [CI configuration](https://github.com/castor-software/depclean/blob/master/.travis.yml#L9) instead of `maven.compiler.release` with JDK 11 would be a valid solution just as the one I suggested (that by the way does not required any code change).

**Comment by rvsoni** [comment] 2021-01-16 05:26
Yes, @amottier, you are correct on fixing this issue by fixing the CI Config to use JDK 8 (i guess OpenJDK) and the correct maven setting will fix this issue, 

Note. The entire project has to be re-release (with the new version) to the public maven repo to make it enable to use on JDK8.

**Comment by ikysil** [comment] 2021-02-09 13:13
This issue is still reproducible with JDK 8

**Comment by rvsoni** [comment] 2021-02-09 16:40
@ikysil 

This plugin is yet not released with the fix, so the artifacts on the maven repo are not compatible with JDK 8,

Ravi

**Comment by mtorres10** [comment] 2021-03-16 20:54
@rvsoni, @cesarsotovalero  and all team castor-software, want to say this project sounds like a fantastic idea.

I made the changes mentioned by @rvsoni [on this branch](https://github.com/mtorres10/depclean/tree/feature/jdk8support) built locally to use with a JDK 8 project.

When using it locally I am getting an error related to nio:

> [ERROR] Failed to execute goal se.kth.castor:depclean-maven-plugin:2.0.1-SNAPSHOT:depclean (default-cli) on project TALOSJava: Execution default-cli of goal se.kth.castor:depclean-maven-plugin:2.0.1-SNAPSHOT:depclean failed: An API incompatibility was encountered while executing se.kth.castor:depclean-maven-plugin:2.0.1-SNAPSHOT:depclean: java.lang.NoSuchMethodError: java.nio.file.Path.of(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;

I compiled using adopt-openjdk hotspot version 282

Can you please point me in the right direction (maybe the branch you used, could help), as I am unsure if I missed something. I cleaned my repository before installing the version with the changes.

My only changes are the following: https://github.com/mtorres10/depclean/blob/56c4cef4c42e2c45de7a37c6ab33c6ae1c283ac6/pom.xml#L20-L22 

Appreciate your help with this,

Marco

**Comment by mtorres10** [comment] 2021-03-16 21:27
@cesarsotovalero Closed PR as it seems more changes are needed in order to support JDK8 on version 2.0.1-snapshot. Will update all my findings

**Comment by cesarsotovalero** [comment] 2021-03-16 21:37
Hi @mtorres10. I downgraded to Java 8 in the past to address this issue (see https://github.com/castor-software/depclean/commit/2faeb21a7cd928263cd01e06218e57ec17e2b5ee), but I had to upgrade again to Java 11 since it didn't solve the issue.

**Comment by mtorres10** [comment] 2021-03-16 23:08
@cesarsotovalero I was able to successfully build and execute a using JDK8. These are my findings:

- Change your POM same as your commit.
- You need to change method Path.of to Paths.get, [see this link](https://stackoverflow.com/questions/60616244/replace-nio-file-pathofstring-for-java-8).
- You need to clean any previous installation you did on your mave repo (I deleted the corresponding folder in my .m2 folder).
- You need to do a mvn clean for each project in the depclean solution (not sure this is strictly required but I did it).
- You need to build/compile using JDK 8 (I used adoptjdk-hotspot 282).

After following those steps I was able to use on a JDK 8 based project without any issues.

**Side note:** on another project I got some errors when plugin de-compresses some jars (just in a couple of them, not all) and json file was not generated. In order to discard it was due using JDK 8 I migrated that project to JDK 11 and tested using depclean for JDK 11 (straight out of the maven repo) with the same results. (I will take a look to this)

Depclean is a great idea and enabling JDK 8 will open even more opportunities for its usage.

**Comment by amottier** [comment] 2021-03-17 08:45
@mtorres10 your PR looks good to me but as [CI is configured to use OpenJDK 11 for the build](https://github.com/castor-software/depclean/blob/master/.travis.yml#L9) I would recommend to update the `pom.xml` to use:
```
<maven.compiler.release>8</maven.compiler.release>
```
instead of
```
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```

[JEP 247](http://openjdk.java.net/jeps/247) mention that `--release N` is equivalent to `-source N -target N -bootclasspath <documented-APIs-from-N>` (for N < 9) and this `-bootclasspath` option is important if build is done on OpenJDK 11 in order to prevent issue with `java.nio.ByteBuffer`.

I open #45 as an alternative that used the solution I'm suggesting in my comment.

**Closed** 2021-03-17 12:01 UTC
Labels: bug

**Comment by amottier** [comment] 2021-03-17 14:09
@cesarsotovalero thanks for merging the PR :+1: Do you plan to release a 2.0.1 built with this modification? I'm asking because for users who want to use the plugin with Java 8 they currently still need to download the source and build from sources the plugin.

**Comment by cesarsotovalero** [comment] 2021-03-17 14:44
Minor is coming soon...
